table godytec_ghl_clinic_leads
	lineageTag: fa69e608-6809-4edb-b3da-4555d1c0068b

	measure 'Total Leads' = COUNTROWS(godytec_ghl_clinic_leads)
		formatString: 0
		lineageTag: 984cc2c6-8e99-46a8-b486-d58fc619411b

		changedProperty = IsHidden

	measure 'Won Leads' =
			
			CALCULATE(
			    [Total Leads],
			    godytec_ghl_clinic_leads[lead_status] = "Won"
			)
		formatString: 0
		lineageTag: ef4dc7e0-e618-49df-a86e-01a9bf0a3566

	measure 'Lost Leads' =
			
			CALCULATE(
			    [Total Leads],
			    godytec_ghl_clinic_leads[lead_status] = "Lost"
			)
		formatString: 0
		lineageTag: 83739f30-e141-4c34-9d53-0fec7df4808d

	measure 'Open Leads' =
			
			CALCULATE(
			    [Total Leads],
			    NOT godytec_ghl_clinic_leads[lead_status] IN { "Won", "Lost" }
			)
		formatString: 0
		lineageTag: ea68a8db-6563-412b-872a-45b5ff14f958

	measure 'Conversion Rate' =
			
			DIVIDE(
			    [Won Leads],
			    [Total Leads],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f821bd59-b42c-44be-901c-9a158758a68c

	measure 'Potential Revenue' =
			
			SUM(godytec_ghl_clinic_leads[estimated_monthly_value_brl])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 1ba41f3c-8a57-4e09-a58a-0ac8a5f4c6dc

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Won Revenue' =
			
			CALCULATE(
			    [Potential Revenue],
			    godytec_ghl_clinic_leads[lead_status] = "Won"
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f031f58a-9db7-4e08-a162-0d3f5d6797da

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Average Ticket' =
			
			AVERAGE(godytec_ghl_clinic_leads[estimated_monthly_value_brl])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 60c4e76a-23cd-4ac2-887f-b8ec6abcb4a0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Average Lead Score' =
			
			AVERAGE(godytec_ghl_clinic_leads[lead_score])
		lineageTag: d59e37d7-0a9f-45d4-be06-34ec40dffa13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Close Probability' =
			
			DIVIDE(
			    AVERAGE(godytec_ghl_clinic_leads[probability_to_close]),
			    100,
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6c05120a-74c0-4027-b316-eebe258e388a

	column lead_id
		dataType: string
		lineageTag: 2d1f8e44-c245-429b-b99c-fa385b47c240
		summarizeBy: none
		sourceColumn: lead_id

		annotation SummarizationSetBy = Automatic

	column clinic_name
		dataType: string
		lineageTag: 98f7f622-ba96-4b46-8978-6c8c2c303476
		summarizeBy: none
		sourceColumn: clinic_name

		annotation SummarizationSetBy = Automatic

	column contact_name
		dataType: string
		lineageTag: 07e7dafc-dd57-45ec-b5af-9dde3e46e2c1
		summarizeBy: none
		sourceColumn: contact_name

		annotation SummarizationSetBy = Automatic

	column contact_role
		dataType: string
		lineageTag: 69f73b2d-d356-4777-9807-07a56d018c9d
		summarizeBy: none
		sourceColumn: contact_role

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: d2bed48a-b7ef-4e10-89d5-666b4eb825dd
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 9685f5f2-bc9e-4489-a0ee-3c740f1d38ef
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: e16961ae-b2d0-450b-8f4b-ad9da80ddcc3
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: b491dea1-d6d2-4dfe-ad72-de0858ef893f
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column clinic_type
		dataType: string
		lineageTag: b5db7d27-1a86-40ee-a139-e0c70bdd3f88
		summarizeBy: none
		sourceColumn: clinic_type

		annotation SummarizationSetBy = Automatic

	column team_size
		dataType: int64
		formatString: 0
		lineageTag: a6c070e4-54cb-406e-ba23-b11157dc4a08
		summarizeBy: sum
		sourceColumn: team_size

		annotation SummarizationSetBy = Automatic

	column monthly_patient_volume
		dataType: int64
		formatString: 0
		lineageTag: e76954c9-cdaa-4657-9f30-d47786f896d8
		summarizeBy: sum
		sourceColumn: monthly_patient_volume

		annotation SummarizationSetBy = Automatic

	column main_interest
		dataType: string
		lineageTag: e768311a-7fc3-45a4-987c-dfbf9a685f1b
		summarizeBy: none
		sourceColumn: main_interest

		annotation SummarizationSetBy = Automatic

	column lead_source
		dataType: string
		lineageTag: a2ef9d17-b087-4396-a454-8a90e91ec16a
		summarizeBy: none
		sourceColumn: lead_source

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 0c96faa6-0971-4017-95c2-1762a94fece5
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column pipeline_stage
		dataType: string
		lineageTag: 7aa6596a-8db5-4e43-bb81-f4e79da0689d
		summarizeBy: none
		sourceColumn: pipeline_stage

		annotation SummarizationSetBy = Automatic

	column lead_status
		dataType: string
		lineageTag: 3d3652eb-6424-401c-a6a1-d2738ee6a05b
		summarizeBy: none
		sourceColumn: lead_status

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06a2f1f2-8c27-4809-bcf8-0813b9581b02
		summarizeBy: none
		sourceColumn: created_date

		variation Variation
			isDefault
			relationship: 2cd4b195-dc4c-48af-8146-993492133f8d
			defaultHierarchy: LocalDateTable_1627940b-7c41-485c-a437-6e91e36f8a86.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_activity_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95b4af2a-1ad1-4913-bc43-4fde4b58404c
		summarizeBy: none
		sourceColumn: last_activity_date

		variation Variation
			isDefault
			relationship: 8058f7b8-006f-43c5-a5b3-12c16c329a71
			defaultHierarchy: LocalDateTable_7dc2bbd4-8f05-41b4-8b77-6c62d54d3bc4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column next_follow_up_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72f4d98e-976e-466c-9eeb-19ef2590964c
		summarizeBy: none
		sourceColumn: next_follow_up_date

		variation Variation
			isDefault
			relationship: 3d0290ea-f3f2-4955-9e80-a1baec5bc4fa
			defaultHierarchy: LocalDateTable_f8970ff7-c495-47b4-96e6-bf9cc0c1a7c9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column estimated_monthly_value_brl
		dataType: int64
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 6080c1e4-6dd8-4b83-af8f-c74e6e7cd2d9
		summarizeBy: sum
		sourceColumn: estimated_monthly_value_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column lead_score
		dataType: int64
		formatString: 0
		lineageTag: 32e676ff-7697-42e9-802d-f965c2d731a7
		summarizeBy: sum
		sourceColumn: lead_score

		annotation SummarizationSetBy = Automatic

	column probability_to_close
		dataType: int64
		formatString: 0
		lineageTag: ae95db38-e0f5-493f-b150-96d8c0399a12
		summarizeBy: sum
		sourceColumn: probability_to_close

		annotation SummarizationSetBy = Automatic

	column lost_reason
		dataType: string
		lineageTag: 31f44128-11db-43bd-8597-751548dd35a1
		summarizeBy: none
		sourceColumn: lost_reason

		annotation SummarizationSetBy = Automatic

	column notes
		dataType: string
		lineageTag: b100377d-f81e-48e8-a392-719c57146077
		summarizeBy: none
		sourceColumn: notes

		annotation SummarizationSetBy = Automatic

	partition godytec_ghl_clinic_leads = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\julia\Desktop\bot_godytec\data\godytec_ghl_clinic_leads.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"lead_id", type text}, {"clinic_name", type text}, {"contact_name", type text}, {"contact_role", type text}, {"email", type text}, {"phone", type text}, {"city", type text}, {"state", type text}, {"clinic_type", type text}, {"team_size", Int64.Type}, {"monthly_patient_volume", Int64.Type}, {"main_interest", type text}, {"lead_source", type text}, {"campaign_name", type text}, {"pipeline_stage", type text}, {"lead_status", type text}, {"created_date", type date}, {"last_activity_date", type date}, {"next_follow_up_date", type date}, {"estimated_monthly_value_brl", Int64.Type}, {"lead_score", Int64.Type}, {"probability_to_close", Int64.Type}, {"lost_reason", type text}, {"notes", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

